### ISSUE TITLE
No Facebook/Twitter login

### ISSUE THREAD

**Issue by steff1193** [Urigo/meteor-angular2.0-socially#155]
https://www.angular-meteor.com/tutorials/socially/angular2/user-accounts-authentication-and-permissions states that it will tell how to "setup OAuth login for Facebook & Twitter". Unfortunately it does not. I would love to see it do so, as I am looking for an working example of Facebook/Twitter login with meteor/angular2/ionic2. Hope it will some day be added!

**Comment by dotansimha** [comment]
Hi @steff1193 ,
This issue is more related to [angular2-meteor-accounts-ui](https://github.com/Urigo/angular2-meteor-accounts-ui) package, and should be implemented there. 
Please follow this issue in order to know more about the packages and it's missing features: https://github.com/Urigo/angular2-meteor-accounts-ui/issues/8

I'm closing this issue since it's related the accounts package.

I will update to tutorial description and add a note about it. 

Thanks.
