### ISSUE TITLE
step 13 - missing how to configure  accounts-ui to implement username instead of email. 

### ISSUE THREAD

**Issue by elpddev** [Urigo/meteor-angular2.0-socially#160]
Hi 
The pipe presents username or email when username not present. 

The summary suggests there was a step to change the account-ui so that we could see username in action in the pipe. 

"configuring our accounts-ui package"

Is it missing? or if it is not, it should be a nice addition so the pipe relevance could be seen.

**Comment by dotansimha** [comment]
Hi @elpddev 
Meteor's accounts package does have support for login with username, but the angular2-meteor-accounts-ui package does not have the support for login/signup with username, since this package created only for bootstrapping a project and for easy start with Angular2-Meteor and accounts packages.
In the most recent tutorial, there is not configuration needed for accounts-ui.
