### ISSUE TITLE
step 5 - how to subscribe multiple params 

### ISSUE THREAD

**Issue by FaberNa** [Urigo/meteor-angular2.0-socially#163]
In step 5 we learn how to map parameter through url in details, but i have more doubt, if i have more parameters than partyId how to subscribes to the other one : 
This is the original code ; 
`
ngOnInit() {
    this.paramsSub = this.route.params
      .map(params => params['partyId'])
      .subscribe(partyId => this.partyId = partyId);
  }
`
If i add to params my new parameter how to add this one to the subscription ??  
I try this way, but in subscription there was an error : 
`
ngOnInit() {
    this.paramsSub = this.route.params
      .map(params => params['partyId','new'])
      .subscribe(partyId,new =>{ this.partyId = partyId});
  }
`
Thanks a lot

**Comment by dotansimha** [comment]
Hi @FaberNa ,

Angular 2, Angular2-Meteor and MeteorObservable uses RxJS Observable, which have `subscribe` method. In the example you mentioned, the `this.route.params` is part of Angular 2 Router, and it's an `Observable` that has `subscribe` method, that triggers the callback each time that the Route params changes. 
So if you want to get multiple params from the Router parameters, you need to remove the `.map()` operator, and just use the original value as array: 

``` js
this.paramsSub = this.route.params.subscribe(params => {
    this.partyId = params['partyId'];
});
```

When you mentioned multiple params for the subscription, I guess that you talked about Meteor subscription for server-side data.
This might be confusing since Meteor has a `subscribe` method of it's own, that does a whole another thing than `Observable.subscribe`. 
In this case, if you want to pass multiple params to Meteor subscription, you need to use:

``` js
Meteor.subscribe(10, "Test", {
   onReady: () => {
        // Subscription is ready
   }
});
```

If you are using `meteor-rxjs` package (MeteorObservable), then you get the same API from Meteor, but with a Observable as return value, so that means that if you use `MeteorObservable.subscribe`, you need to add another `subscribe` on the return value:

``` js
MeteorObservable.subscribe(10, "Test").subscribe(() => {
     // Subscription is ready
});
```

Please re-open the issue of you have any other questions!

**Comment by 0mkara** [comment]
Thanks @dotansimha for this solution. This was not mentioned anywhere else. Really helped me.
