### ISSUE TITLE
Step 18 - angular-material : Flex and layout not working

### ISSUE THREAD

**Issue by kenp77** [Urigo/meteor-angular2.0-socially#168]
The 'flex' and 'layout' directives are not working after i followed the 'Step 18 - angular-material and custom Angular auth forms'.
All the layout is missed up and is not displayed like shown in the video Demo ! I followed the tutorial step by step and i also download the zip file but the Flex and layout are not recognized !! Thus the layout is kind of ugly :(

**Comment by dotansimha** [comment]
Yeah @kenp77. The layout issue started in the recent updates of the tutorial, caused by an update in Angular2-Material package. 
Angular2-Material packages hasn't implemented yet layout, grids, md-content, flex, columns and whiteframe (elevation) yet, and you can track it's progress in https://github.com/angular/material2/issues/946.

I will add some basic CSS to the tutorial to make it look better, and when angular2-material will add support for those missing features - we will update it in the tutorial

Thanks @kenp77 .

**Comment by dotansimha** [comment]
I fixed it by using Angular1-Meteor stylesheet for layout, and added some missing CSS styles, now it looks fine.

Thanks again @kenp77 .

**Comment by kenp77** [comment]
mmm...what did you update exactly ? The tutorial it self or the zip file ? because i dont see the changes yet in both the tutorial and the zip file.  It take a delay so i can see the changes ?

**Comment by dotansimha** [comment]
@kenp77 Yeah sorry I did not have the time last week, I will update it today..
