### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by zh-wowtv** [Urigo/meteor-angular2.0-socially#169]
I followed the tutorial until step 20. But the image upload doesn't work. Here is the screenshot:

<img width="836" alt="2016-10-14 2 19 17" src="https://cloud.githubusercontent.com/assets/18462946/19377513/6c5c55bc-9219-11e6-8b63-035c931efe96.png">

There is no error message in browser console and in meteor console.

Any suggestion? Thanks.

**Comment by dotansimha** [comment]
@zh-wowtv 

It looks like you need to install ImageMagick, as described in the tutorial:

```
Note: To use this module, you need download and install GraphicsMagick or ImageMagick. In Mac OS X, you can use Homebrew and do: brew install graphicsmagick or brew install imagemagick.
```

Otherwise, the thumbnails won't work. 

Please try to create the actual party - you should see the image in the parties list, because there we use the regular store instead of the thumbnails store. 

Please reopen if you still have another issues. 

Thanks.

**Comment by Urigo** [comment]
@zh-wowtv also if something wasn't clear enough in the tutorial, please suggest edits so it will be more clear to future developers, thank you!

**Comment by zh-wowtv** [comment]
@Urigo Thanks for your reply. I installed everything you mentioned but the image resize still doesn't work in my local machine. 

By the way, is there any other way to resize image? Because it's not possible to install ImageMagick or GraphicsMagick globally in my deployment (openshift).
