### ISSUE TITLE
Got compiling problem

### ISSUE THREAD

**Issue by zh-wowtv** [Urigo/meteor-angular2.0-socially#170]
It seems there is no problem in previous version. But I got this in new version.

<img width="392" alt="2016-10-15 11 24 20" src="https://cloud.githubusercontent.com/assets/18462946/19411184/75ce421a-932f-11e6-9c44-b983c0550ce6.png">

It shows "Cannot find module" and  "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning." But I can run it without any problem.

Any idea? Thanks.

**Comment by anode7** [comment]
Hi @zh-wowtv ,
you must configure your IDE to execute version 2.0.\* of typescript.
Given what you expose it executes version 1.8 and in your project in `node_modules/typescript/lib` it's 2.0.3
What's your IDE/system ?

**Comment by zh-wowtv** [comment]
@anode7 How to check? 

I'm running the latest version of vs code.

**Comment by anode7** [comment]
[watch here the official doc](https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions)
you must add `"typescript.tsdk": "./node_modules/typescript/lib"`  in your project config file (.vscode/settings.json)
checked that he comes to the latest version of typescript in `./node_modules/typescript/`

**Comment by dotansimha** [comment]
Hi @zh-wowtv , 
As @anode7 said, if you are using VSCode there are some configuration you need to do in order to work with TypeScript 2. 
This isn't related to Angular2-Meteor socially directly. 
Please try to use @anode7 solution and configure you IDE, if there is another issues with the tutorial, please open a new issue. 

Thanks and good luck!

**Comment by zh-wowtv** [comment]
It doesn't work after I setup as you guided. And I found there is no `typescript` folder in `./node_modules` at all.

What I don't understand is that there is no problem before your latest commit.

Then I did the following:

> npm install typescript -D

It still the same.

**Comment by anode7** [comment]
run `npm view typescript version` 
to check you well using version 2 of typescript. ( if < run `npm -g i typescript@next`)
if the return is 2.0.3 and you have not installed typescript in your local node_modules , you can delete the .vscode/settings.json
and as you well checked uses version 1.6.1 of vscode (with typescript 2) 
Following the instructions on the official website of vscode

**Comment by zh-wowtv** [comment]
@anode7 
- `npm view typescript version` return 2.0.3
- I don't have `.vscode/settings.json`
- My vs code is 1.6.1

But the problem still exists.

**Comment by anode7** [comment]
@zh-wowtv 
I just do the test new fresh clone ... and I get the same result as you.
The problem is the replacement of  "typings" to "meteor-typings" [ccb5346](https://github.com/bsliran/angular2-meteor-base/commit/ccb5346e7b96361e868f6ae80144c29fdfc39420) .
You can make a clone of Urigo/meteor-angular2.0-socially repository , you'll see that everything goes well

**Comment by zh-wowtv** [comment]
Removing `files` in tsconfig.json solves the problem.
