### ISSUE TITLE
app broken with updated versions

### ISSUE THREAD

**Issue by netanelgilad** [Urigo/meteor-angular2.0-socially#35]
Hey,
I just tried running the app from a clean clone.
I ran:
`meteor update`
`meteor`

and I get the following error in the console:
![image](https://cloud.githubusercontent.com/assets/3474905/12458516/e0504f8a-bfb2-11e5-8bdf-0bb467b238b3.png)

**Comment by barbatus** [comment]
pls update

**Comment by TrikinCurt** [comment]
barbatus,  sorry to put this on the socially git issue list, but i am making a new project and getting the exact error.  meteor update states i have the latest.

I am not export on the packaging system (figure 1.3 will be soon and happily will never learn it), but here is what I see for versions:

barbatus:angular2@0.8.0
barbatus:ng2-compilers@0.1.1
barbatus:ts-compilers@0.2.6
barbatus:typescript@0.1.5
urigo:angular2-meteor@0.3.8

**Comment by TrikinCurt** [comment]
Ok, since this was MY app I copied my old app.ts file, I see the change:

import {bootstrap} from 'angular2-meteor';

I get it since you use a custom bootstrap, but I didn't notice the syntax change, once i switched that, everything runs like a champ.

So in love right now!  With angular2-meteor, I just met all of of you :)  So I would think this could be closed, as I can verify it works great.

**Comment by netanelgilad** [comment]
Awesome! 
Update the tutorial as well, since the example there in the first step uses the wrong bootstrap..
