### ISSUE TITLE
Try to let this run under meteor 1.3 with no luck

### ISSUE THREAD

**Issue by rvetere** [Urigo/meteor-angular2.0-socially#54]
Hi there, i'm desperately trying to get ng2 running under meteor 1.3 setup - because i urgently need native ES6 module support (i can't import dragula with a simple "import \* from 'dragula'" otherwise)

so.. i'm really having a hard time getting into this topic because.. i can read many infos about the awesomness of meteor 1.3 - but no single example showing me how to transform an existing project into it.

Now i started over one more time with this project as a clean starting point. First, updating all dependent packages so the app can run -> check, works, yess..

Then updating meteor to 1.3 with `meteor update --release 1.3-modules-beta.8`

And after a new start of the app without any complains, my browser is exploding:

https://www.dropbox.com/s/ydjylmpe0uca687/Screenshot%202016-03-21%2016.48.16.png?dl=0

He's clearly missing system.js (what i don't want to use anyway, +1 for that) - but how can i shift the project to work again? Somehwere i read that the angular2-meteor atmosphere package will be obsolete and be replaced by an npm version one, or that i can use the angular2-npm package directly...

All nice infos but is anywhere a project seed in the web actually showing of a running example? :)

**Comment by u0m3** [comment]
As far as I remember Meteor 1.3 has some breaking changes one of witch is using _CommonJS_ instead of _SystemJS_. At a first glance the problem you show in the screens shot seems to be related to this. You can check for sure by changing **tsconfig.json** as stated [here](https://atmospherejs.com/urigo/angular2-meteor#typescript).
Also read the rest of that page as it clearly states that the tutorial is made for _Meteor 1.2_ and it also lists the major changes when using _Meteor 1.3_ ([direct link](https://atmospherejs.com/urigo/angular2-meteor#quick-start))

Hope this helps you fix at least some of the issues. Also keep in mind that some versions of chrome have issues with some Meteor components (don't really know what, but for example I use Chrome Dev and for a few versions http://atmospherejs.com/ was broken; http://www.angular-meteor.com/ is still semi-broken). Try testing on more than one browser when you encounter strange errors (for me Firefox stable works).

**Comment by rvetere** [comment]
Ah sorry i totally forgot about this issue - i solved it in the meanwhile by following the guide of Hongbo-Miao here: https://github.com/Urigo/angular2-meteor/issues/180

Well i did not get this demo app running under 1.3, but i'm having now my own ng2 prototype running what i actually wanted to achieve, can be closed for me at the moment ;)
