### ISSUE TITLE
Access the Meteor collections from the browser command line

### ISSUE THREAD

**Issue by jacobdr** [Urigo/meteor-angular2.0-socially#6]
With Angular2-Meteor using the System.register syntax, are Meteor Mongo collections no longer available as global objects that can be accessed from the browser console? And if not, is there a way to use a getter from the console to return the collection?

Running something like `var Parties = parties` or `var Parties = new Mongo.Collection('parties')` in Angular1-Meteor would allow one to insert/modify/delete records from the browser console which I found useful for debugging purposes, and trying to figure out how to access the same functionality here.

**Comment by barbatus** [comment]
You can still define global objects with System.js. For example, instead of `export var Parties = Mongo.Collection('parties')` just use `Parties = Mongo.Collection('parties')`. Then import `collection/parties`  to define this global variable: `import 'collection/parties'`.

Another one option you may consider is to use  some debugging tools like [mongol](https://atmospherejs.com/msavin/mongol)

**Comment by simonv3** [comment]
As far as I'm aware you can still access Parties etc from the console. What do you see when you open the console and type `window`?

**Comment by barbatus** [comment]
@simonv3 you can if `Parties` is a global variable otherwise if defined in a module it's local to this module.

**Comment by simonv3** [comment]
@barbatus ah gotcha
